# Site settings
title: Jared Desjardins
email: jared.desjardins@colorado.edu
description: null # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog/
url: http://jared-desjardins.github.io/ # the base hostname & protocol for your site
# twitter_username: null
# github_username:  jared-dejardins

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  #portfolio:
    #output: true
    #permalink: /portfolio/:path/
  #poetry:
    #output: true
    #permalink: /poetry/:path/
  pages:
    output: true
    permalink: /pages/:path/
